Code of Conduct in Textdatei formuliert ; in README dokumentiert
RF-Buerky/BBFW-Project pull request #14
Opened 2017-07-31 16:25 UTC by RF-Buerky

Vorschlag für die Lösung von Issue #7 

Da wir ein kleines unbedeutendes Projekt führen können wir uns beim Verhaltenskodex recht kurz fassen, denke ich. Unsere Arbeit wird wohl kaum in der breiten Öffentlichkeit präsentiert werden sonst irgendie sonderlich bekannt werden, sodass unser Verhalten vorbildlich sein müsste ^^. 

Aus dem Grund habe ich den Verhaltenskodex kurz gehalten. Der Verhaltenskodex steht in der neu eingefügten Textdatei "Code of Conduct.txt". In der [README](https://github.com/RF-Buerky/BBFW-Project/blob/master/README.md "Link zur README") ist auf den Verhaltenskodex verwiesen worden.

2017-07-31 18:36 UTC, nipafx requested changes

2017-07-31 18:36 UTC, nicolaiparlog commented on Code of Conduct.txt
> +- Die Mitwirkenden verschreiben sich dem obersten Ziel, möglichst viele Aufgaben zu lösen.
Vielleicht wollen Teilnehmer Aufgaben lieber "möglichst gut" lösen. :wink: Ich denke nicht, dass die Art und Weise, wie an Aufgaben herangegangen wird, festgehalten werden muss.

2017-07-31 18:36 UTC, nicolaiparlog commented on Code of Conduct.txt
> +- Die Bearbeitung der Aufgaben erfolgt rücksichtsvoll bezüglich der individuellen Benotung. Die Aufgaben sollen nach Möglichkeit gleichmäßig durch die Projekteigner bearbeitet werden können. Erstellt
Gute Idee, das aufzunehmen.

2017-07-31 18:36 UTC, nicolaiparlog commented on README.md
> +Für den Ausschluss eines Mitwirkenden ist eine absolute Mehrheit der Projekteigner von Nöten. Handelt es sich bei dem Beschuldigten um einen Projekteigner, so ist dieser nicht Stimmberechtigt. Ein Au
Da die Teilnahme an diesem Projekt entscheidend für das Bestehen des Kurses ist, kann die Gruppe niemanden davon ausschließen. Wenn sich jemand unangemessen verhält und vorsichtige (!) Hinweise darauf nichts ändern, wendet euch bitte an mich.

PS: Ich fühl mich mit meinem neuen Spitznamen nicht wohl.

2017-07-31 18:36 UTC, nicolaiparlog commented on Code of Conduct.txt
> +Zusammenfassend gelten an ersten Stelle Recht und Gesetz der BRD, des Weiteren die grundlegenden sozialen Regeln der BRD und der "gesunde Menschenverstand".
Der Grund für die meisten Auseinandersetzungen ist, dass Leute unterschiedliche Vorstellungen von sozialen Regeln und gesundem Menschenverstand haben. Deswegen beschreibt ein CoC meist explizit, was ok ist und was nicht. Das müsst ihr aber nicht selber ausformulieren - ich dachte eher, dass ihr einen existierenden CoC übernehmt. Müsst ihr aber nicht und der hier ist auch weitestgehend in Ordnung (siehe unten, was geändert werden muss).

2017-07-31 18:40 UTC, nicolaiparlog commented
Noch was: Wenn du die Datei `CODE_OF_CONDUCT.md` nennst, erkennt GitHub, dass das Projekt einen CoC hat und zeigt das irgendwo an (glaube ich).

2017-07-31 20:45 UTC, nicolaiparlog commented
Gute Arbeit und gute Commit-Historie. Vergiss nicht, die README noch anzupassen.

:bulb: Die meisten meiner Kommentare oben klappt GitHub ein, weil diese Zeilen mittlerweile verändert wurden. Kommentare auf unangetasteten Zeilen bleiben ausgeklappt - so kann man einfach sehen, was noch nicht adressiert wurde.

2017-07-31 20:47 UTC, RF-Buerky commented on README.md
> +Für den Ausschluss eines Mitwirkenden ist eine absolute Mehrheit der Projekteigner von Nöten. Handelt es sich bei dem Beschuldigten um einen Projekteigner, so ist dieser nicht Stimmberechtigt. Ein Au
Ok das glaub ich gern. Anfangs war es sogar noch komplett deutsch - Gott des Kodes. Das war mir dann doch schon etwas zu herb. 😆 

Bin dran an der anderen Formulierung...

2017-08-01 07:21 UTC, nipafx approved these changes

2017-08-01 07:21 UTC, nicolaiparlog commented
:+1:

2017-08-01 12:10 UTC, merged