Maven Kotlin Projekt alias mkp
RF-Buerky/BBFW-Project pull request #18
Opened 2017-08-01 14:21 UTC by jwustmann

Ein neues Projekt wurde in IntelliJ erstellt und enthält nun eine HelloWorld Funktion; das ganze ist als Maven-Projekt erkannt

2017-08-01 14:27 UTC, nicolaiparlog commented
Sieht gut aus, kann ich aber frühestens heute Abend ausprobieren.

2017-08-01 15:13 UTC, RF-Buerky reviewed
Kleine Anmerkungen, siehe unten

2017-08-01 15:13 UTC, RF-Buerky commented on pom.xml
> +		<main.class>org.codefx.demo.bingen.energy_model.MainKt</main.class>
Hier in Zeile 15 wäre noch der Name anzupassen. Glaube der kann völlig beliebig sein.

2017-08-01 15:13 UTC, RF-Buerky commented on pom.xml
> +		<testSourceDirectory>${project.basedir}/src/test/kotlin</testSourceDirectory>
Das Testverzeichnis müssen wir dann nachher noch erstellen bei Issue #11

2017-08-01 15:13 UTC, RF-Buerky commented on src/main/kotlin/traffic_simulation/HelloWorld.kt
> +
Glaube damit man einen Test schreiben kann, müsste eine neue, eigene Funktion geschrieben werden, mittels der einer Variable der Ausgabe-String "Hello, World!" zugewiesen wird.

Bin mir da aber nicht sicher. @nicolaiparlog

2017-08-01 15:19 UTC, jwustmann commented on pom.xml
> +		<testSourceDirectory>${project.basedir}/src/test/kotlin</testSourceDirectory>
Darum kümmere ich mich hier dann nicht; die zu erstellenden Ordner lassen sich über git wohl nicht pushen.

2017-08-01 15:20 UTC, jwustmann commented on pom.xml
> +		<main.class>org.codefx.demo.bingen.energy_model.MainKt</main.class>
Wird angepasst

2017-08-01 16:55 UTC, RF-Buerky commented
Die .jar wie sie am Ende sein soll für den Release können wir erst erstellen wenn der die Test-Datei eingebunden ist.

Denke daher müsste man erst diesen PullRequest mergen (mit nicht fertiger .jar), die Tests mergen und dann in einem neuen Schritt / neuer Issue die .jar nochmal erstellen.

2017-08-01 18:26 UTC, nicolaiparlog commented on pom.xml
> +		<testSourceDirectory>${project.basedir}/src/test/kotlin</testSourceDirectory>
Git kann nur Dateien, leere Ordner funktionieren da nicht.

Am Ende jedes Pull Requests sollte das Projekt in einem konsistenten Zustand sein. Hier Tests zu deklarieren, die es noch nicht gibt und Dependencies zu deklarieren, die nicht benötigt werden (JUnit, weiter oben) erfüllt diese Bedingung nicht. :smiley: Nehmt bitte alle testbezogenen Teile aus der POM raus.

2017-08-01 18:27 UTC, nicolaiparlog commented on src/main/kotlin/traffic_simulation/HelloWorld.kt
> +
Eigentlich soll ein Test etwas sinnvolles testen. Im Rahmen dieses Issues sind Tests aber noch gar nicht notwendig, und selbst in #11 reicht es einen Test zu erstellen, der nichts aufruft außer `println`.

2017-08-01 18:28 UTC, nicolaiparlog commented
Die JAR soll sowieso nicht eingecheckt werden. Es soll nur möglich sein sie zu bauen.

2017-08-01 18:37 UTC, nipafx requested changes

2017-08-01 18:37 UTC, nicolaiparlog commented on pom.xml
> +		<main.class>BBFW-Project</main.class>
Das muss der Name der Klasse sein, die die `main` Methode enthält, sonst kann man die erstellte JAR nicht mit `java -jar ${path/to/JAR/file}` ausführen.

2017-08-01 18:37 UTC, nicolaiparlog commented on pom.xml
> +					<execution>
Dieser ganze `execution` Block gehört auch zu #11.

2017-08-01 20:25 UTC, RF-Buerky commented on pom.xml
> +	<version>1.0-SNAPSHOT</version>
Hier wäre es gut den Namen ohne "...-SNAPSHOT" anzugeben. Laut [Wikipedia](https://de.wikipedia.org/wiki/Schnappschuss_(Informationstechnik) "Link zum Wikipeda-Artikel zu Snapshot") ist ein Snapshot "eine Programmversion [...] die nicht als offizielle Version (engl. release) herausgegeben wird". 

Da wir das Projekt nach dem Block 1 releasen wollen könnte es zu Unklarheiten kommen. Lieber nur "1.0", ist auch schön kurz.

2017-08-02 04:46 UTC, nicolaiparlog commented on pom.xml
> +	<version>1.0-SNAPSHOT</version>
Ne, das `-SNAPSHOT` gehört da hin, denn wie du zitierst markiert das Versionen, die nicht released sind. Das gilt für dieses Projekt noch eine Weile - man macht man wirklich erst weg, wenn das Release gemacht und direkt danach auch wieder hin (dann z.B. mit `2.0-SNAPSHOT`).

Der Grund dafür ist, dass Maven nicht zulässt, Versionen zu aktualisieren. Du kannst nicht erst eine Version 1.0 installieren (mit `mvn install`) und nachher eine andere (außer du löschst manuell Dateien). Da man in der Entwicklung aber dauernd `install` aufruft, würde das zu Problemen führen. Das `-SNAPSHOT` am Ende hat diese Beschränkung nicht.

2017-08-02 08:17 UTC, jwustmann commented on pom.xml
> +		<main.class>BBFW-Project</main.class>
Okay, also demnach aktuell unser HelloWorld Programm. Ich Update mal den PR

2017-08-02 13:14 UTC, RF-Buerky commented on pom.xml
> +					<execution>
@jwustmann , @nicolaiparlog 
Soll nur der Block 

-
					<execution>
 						<id>test-compile</id>
 						<goals>
 							<goal>test-compile</goal>
 						</goals>
 					</execution>
</executions>

herausgenommen werden oder mehr? Jetzt in der aktualisierten Version ist der obere Teil rausgenommen worden.

- 					<execution>
						<id>compile</id>
						<goals>
						<goal>compile</goal>
					</goals>
			               </execution>

2017-08-02 13:18 UTC, RF-Buerky commented on pom.xml
> +					<execution>
@jwustmann , @nicolaiparlog 
Soll nur der Block 

-
					<execution>
 						<id>test-compile</id>
 						<goals>
 							<goal>test-compile</goal>
 						</goals>
 					</execution>
</executions>

herausgenommen werden oder mehr? Jetzt in der aktualisierten Version ist der obere Teil rausgenommen worden.

- 					<execution>
						<id>compile</id>
						<goals>
						<goal>compile</goal>
					</goals>
			               </execution>

2017-08-02 13:23 UTC, RF-Buerky commented on pom.xml
>  						<id>test-compile</id>
@jwustmann , @nicolaiparlog 
Ist da der richtige Block entfernt worden?
gelöscht wurde:

-
					<execution>
 						<id>test-compile</id>
 						<goals>
 							<goal>test-compile</goal>
 						</goals>
 					</execution>
</executions>

vielleicht hatte sich Nicolais Hinweis auf die sich unter dem Kommentar öffnende execution bezogen. Diese: 

- 					<execution>
						<id>compile</id>
						<goals>
						<goal>compile</goal>
					</goals>
			               </execution>

2017-08-02 13:43 UTC, nicolaiparlog commented
Probier's mal aus und guck mit `java -jar target/traffic_simulation-1.0-SNAPSHOT-jar-with-dependencies.jar` in das JAR. :smiley:  Guck danach noch mal genau in die POM des Energy Model.

2017-08-02 14:08 UTC, jwustmann commented
@nicolaiparlog Mit der Methode des ganz genauen Hinsehens konnte die zuerst nicht auffindbare Datei ausgeführt werden mit dem Ergebnis der Ausgabe "Hello, World!", indem die Mainclass von HelloWorld.kt in HelloWorldKt geändert wurde

2017-08-02 14:17 UTC, RF-Buerky commented
Bei mir funktionierts 
👍

2017-08-02 14:33 UTC, nicolaiparlog commented
Genau hingucken hilft halt. :wink:

:+1:

2017-08-02 14:34 UTC, jwustmann commented
![Like](https://pbs.twimg.com/media/BmFJThdIIAA5V3W.jpg)

2017-08-02 14:41 UTC, merged