Einfache Simulation erstellen
RF-Buerky/BBFW-Project pull request #40
Opened 2017-08-03 21:57 UTC by jwustmann

Lösungsvorschlag für #20 und #21    Closes #20 Closes #21 

Methoden zur Simulation der Verkehrslage für einen Zeitschritt werden erstellt und eine exemplarische Simulation wird mit einer Liste von 12 Autos durchgeführt. Zum aktuellen Zeitpunkt wird die Liste noch nicht über eine CSV Datei geliefert (Issue #23 )

2017-08-03 22:28 UTC, nipafx reviewed
I took a quick look at the code. From what I can see, it looks like you're getting there.

2017-08-03 22:28 UTC, nicolaiparlog commented on src/main/kotlin/traffic_simulation/roadNetwork.kt
> +class roadNetwork(val capacity : Double){
Class names should beg in with capital letters, i.e. `RoadNetwork`.

2017-08-03 22:28 UTC, nicolaiparlog commented on src/main/kotlin/traffic_simulation/roadNetwork.kt
> +    fun calculateDemand(vehicles:MutableList<vehicle>): Double{
Unless I'm missing something, the `vehicle` class (should be `Vehicle`) is not part of the PR.

2017-08-03 22:28 UTC, nicolaiparlog commented on src/main/kotlin/traffic_simulation/roadNetwork.kt
> +    fun calculateDemand(vehicles:MutableList<vehicle>): Double{
There is no indivation that the vehicles change over the course of the simulation. I recomment making the list of vehicles immutable and defineing it as a field like `capacity`.

2017-08-03 22:32 UTC, jwustmann commented on src/main/kotlin/traffic_simulation/roadNetwork.kt
> +    fun calculateDemand(vehicles:MutableList<vehicle>): Double{
i will consider this points and write my next commits in german again... guess its getting late

2017-08-03 23:30 UTC, jwustmann commented
Die Funktion `scenario(...)` soll in der `main(...)` aufgerufen werden, die durch #34 von @RF-Buerky  erstellt werden würde. Da dort auch `Vehicle` und `RoadNetwork` erstellt werden sollten, ich die Simulation ohne diese Klassen (zumindest ohne RoadNetwork)aber nicht hätte schreiben können, hänge ich später noch einen Commit für eine `main(...)` an, was den ersten Teil PR #34 ebenfalls erfüllen würde.

2017-08-04 07:13 UTC, nipafx requested changes
Sehr gute Arbeit. Hab kleine Anmerkungen zum Code (siehe unten) und zwei andere Wünsche:

* Du solltest noch Tests schreiben. Es sieht so aus als wären `calculateDemand` und `checkForTrafficJam` gut geeignet, um sie zu testen.
* Bitte lösche `HelloWorld` und trag in die POM ein, dass `Main` die Startklasse ist.

2017-08-04 07:13 UTC, nicolaiparlog commented on src/main/kotlin/traffic_simulation/Main.kt
> +    scenario(testList, testRoad)
Es ist typischerweise sinnvoll, "Dinge" (was auch immer "Dinge" im konkreten Kontext genau heißt) dort zu erstellen, wo man sie auch braucht. In diesem Fall wäre es deswegen besser `testList` und `testRoad` in der `scneario` Methode zu erstellen.

2017-08-04 07:13 UTC, nicolaiparlog commented on src/main/kotlin/traffic_simulation/Main.kt
> +    scenario(testList, testRoad)
Übrigens, dass etwas eine Liste ist, ist meistens wesentlich weniger interessant als was in der Liste drin ist. Deswegen braucht mal `List` nicht in den Namen aufzunehmen - außerdem kann mir das ja auch die IDE sagen, wenn ich es wissen will.

2017-08-04 07:13 UTC, nicolaiparlog commented on src/main/kotlin/traffic_simulation/Main.kt
> +    if(road.checkForTrafficJam(road.calculateDemand(vehicleList))){
Die Idee die Logik in `calculateDemand` und `checkForTrafficJam` aufzuteilen ist sehr gut! :+1: Außenstehende (wie hier `Main`) sollten sich damit aber nicht abgegeben im Detail müssen. Wenn das `RoadNetwork` noch eine Methode `simulateTraffic` (oder so) bekäme, könnte diese die beiden Methoden aufrufen.

2017-08-04 11:37 UTC, jwustmann commented on src/main/kotlin/traffic_simulation/Main.kt
> +    scenario(testList, testRoad)
`List`: Ich werde versuchen es für die Zukunft zu berücksichtigen, allerdings hat mir diese intuitive Benennung geholfen den Überblick zu behalten; ich habe mich nicht dazu genötigt gefühlt 💯 👍

2017-08-04 11:55 UTC, nicolaiparlog commented on src/main/kotlin/traffic_simulation/RoadNetwork.kt
> +    fun calculateTraffic (vehicleList: List<Vehicle>, road: RoadNetwork){
Ein Straßennetzwerk braucht kein anderes Straßennetzwerk als Parameter. Das ist zum Einen verwirrend und kann zum anderen sehr schnell zu Bugs führen.

2017-08-04 12:32 UTC, nicolaiparlog commented
Great, now all that's missing are the tests.

2017-08-04 12:35 UTC, nicolaiparlog commented
Oder weißt du was? Merge diesen PR so, damit andere weiterarbeiten können, und schreib die Tests in einem separaten PR. Befor du mergst, musst du dann aber "Closes #20" aus dem Kommentar nehmen, damit das Issue nicht zugeht.

Falls du das so vorhast: :+1:

2017-08-04 12:35 UTC, nipafx approved these changes

2017-08-04 12:44 UTC, dbaumy commented
Ich glaube Nicolai meinte mit entfernen von HelloWorld nur die Änderung in der POM, anstatt den Test selbst zu löschen. !?

2017-08-04 12:45 UTC, merged

2017-08-04 12:45 UTC, RF-Buerky commented
Ja, Test und die normale Kotlin-Datei sind hier gelöscht. Glaube auch war nur auf die pom bezogen

2017-08-04 13:21 UTC, nicolaiparlog commented
`HelloWorld` und `HelloWorldTest` waren nur Platzhalter. `HelloWorld` sollte gelöscht werden und dementsprechend musste die POM angepasst werden. `HelloWorldTest` hätte bis zum PR mit den Tests bleiben können, aber gelöscht ist auch ok.

2017-08-04 13:23 UTC, dbaumy commented
Okay, dann nur der Ordnerpfad für die zukünftigen Tests.

2017-08-04 13:30 UTC, nicolaiparlog commented
Falls du damit meinst, dass ein leerer Ordner `src/kotlin/test` erstellt werden soll, muss ich dich enttäuschen: Git kann keine leeren Ordner. Wir müssen einfach warten bis @jwustmann oder @RF-Buerky mit ihren Pull Requests wieder Tests hinzufügen.

2017-08-04 13:40 UTC, dbaumy commented
Habe ich bemerkt, da nur Dateien geadded werden können. 👁