Code in RoadNetwork in mehrere neue Funktionen verteilt
RF-Buerky/BBFW-Project pull request #83
Opened 2017-08-08 18:55 UTC by RF-Buerky

Beginn der Lösung für Issue #82 
Closes #82 

Es wurden Tests für RoadNetwork geschrieben. Für die Tests wurde die Funktion `calculateDemandAtTimestep` zunächst noch in mehrere neue Unterfunktionen heruntergebrochen.

2017-08-09 08:27 UTC, nipafx requested changes

2017-08-09 08:27 UTC, nicolaiparlog commented on src/main/kotlin/traffic_simulation/Vehicle.kt
> +            this.wannaDriveInHours.add(timestep + 1)
Mit der Zeile können Verspätungen doppelt gezählt werden:

* `delay` wird hochgesetzt und muss nachher wieder abgebaut werden
* außerdem wird jetzt u.U. an einer Stunden gefahren, an der es vorher nicht so war.

Hier sind Tests (können in `VehicleTest`), die das unterstreichen:

```kotlin
@Test
fun delayAndDrive_mixedDelaysAndDriveRequirements_driveRequirementsCorrectlyReported() {
    val tesla = Vehicle(1, mutableListOf(1, 5))
    assertTrue(tesla.vehicleWantsToDriveAt(1))

    tesla.getDelayedAtHour(1)
    // couldn't drive at 1, so wants to drive at 2
    assertTrue(tesla.vehicleWantsToDriveAt(2))

    tesla.getDelayedAtHour(2)
    // again, couldn't drive,  so wants to drive at 3
    assertTrue(tesla.vehicleWantsToDriveAt(3))

    tesla.driveAtHour(3)
    // finally time to drive; this resolves delay from hour 1, so no more driving
    assertFalse(tesla.vehicleWantsToDriveAt(4))

    // wants to drive at hour 5 as per original requirements
    assertTrue(tesla.vehicleWantsToDriveAt(5))
}

@Test
fun delayAndDrive_mixedDelaysAndDriveRequirements_driveRequirementsCarriedAcross() {
    val tesla = Vehicle(1, mutableListOf(1, 2, 4))
    assertTrue(tesla.vehicleWantsToDriveAt(1))

    tesla.getDelayedAtHour(1)
    // couldn't drive at 1 _and_ wanted to drive at 2 anyways
    assertTrue(tesla.vehicleWantsToDriveAt(2))

    tesla.getDelayedAtHour(2)
    // couldn't drive at 1 & 2, so definitely wants to drive at 3
    assertTrue(tesla.vehicleWantsToDriveAt(3))

    tesla.driveAtHour(3)
    // still one hour delayed _and_ wants to drive at 4 anyways
    assertTrue(tesla.vehicleWantsToDriveAt(4))

    tesla.driveAtHour(4)
    // driving at 4 accomplished but still one hour delayed, so wants to drive again
    assertTrue(tesla.vehicleWantsToDriveAt(5))

    tesla.driveAtHour(5)
    // finally all done
    assertFalse(tesla.vehicleWantsToDriveAt(6))
}
```

Die scheitern mit der Zeile, gehen ohne aber durch. Ich habe mir die anderen Tests nicht genau angeguckt, gehe aber davon aus, dass sie fehlerhaft sind.

2017-08-09 08:27 UTC, nicolaiparlog commented on src/test/kotlin/RoadNetworkTest.kt
> +            assertEquals(true, test)
Das ist besser als die Variablen auf zu addieren (wie an anderen Stellen oft gemacht).

2017-08-09 08:27 UTC, nicolaiparlog commented on src/test/kotlin/RoadNetworkTest.kt
> +        assertEquals(18, i)
Warum 18 hier die richtige Zahl ist, ist nicht offensichtlich. Besser du stellst für alle Autos fest, ob alle Stunden nach `19` verspätet sind.

2017-08-09 08:27 UTC, nicolaiparlog commented on src/test/kotlin/RoadNetworkTest.kt
> +        assertEquals(132, i)
Unklar, warum 132 richtig sein sollte. Kurztest: Was ist falsch gelaufen, wenn 36 rauskommt?

<details>
  <summary>Klick hier für die Antwort</summary>
Die von mir angemeckerte Zeile aus <code>Vehicle</code> wurde rausgenommen.
</details>

2017-08-09 08:36 UTC, nicolaiparlog commented on src/main/kotlin/traffic_simulation/Vehicle.kt
> +            this.wannaDriveInHours.add(timestep + 1)
Bezüglich der sich nicht fortpflanzenden Verspätung, wenn man die Zeile wieder rausnimmt: Erinnerst du dich an meinen Kommentar, dass es eine philosophische Frage ist, wann man verspätet ist. Hatte doch konkretere Auswirkungen als ich glaubte...

Zwei Zeilen über der kommentierten passiert dies: `delayedInHours.add(timestep)`. Allerdings nur, wenn zu dem Zeitpunkt ursprünglich gefahren werden wollte (weil es im `if`) ist. Das ist der Fehler, denn man ist natürlich auch verspätet, wenn man aufgrund einer Verspätung fahren wollte, aber es dazu nicht gekommen ist.

2017-08-09 11:14 UTC, RF-Buerky commented on src/test/kotlin/RoadNetworkTest.kt
> +            assertEquals(true, test)
Ok, ich setze diese Art bei den aufaddierenden Tests ein.

2017-08-09 11:16 UTC, RF-Buerky commented on src/test/kotlin/RoadNetworkTest.kt
> +        assertEquals(18, i)
Ja, mit der nun klargestellen Philosophie von `delay` kommt wieder 3 heraus.

2017-08-09 11:17 UTC, RF-Buerky commented on src/test/kotlin/RoadNetworkTest.kt
> +        assertEquals(132, i)
Ja, hier steht nach der klargestellten Philosophie von `delay` nun 36 drin.

2017-08-09 15:26 UTC, RF-Buerky commented
@nicolaiparlog 
Ist dein Change request erfüllt? Fehlt noch was?

2017-08-10 08:19 UTC, nipafx approved these changes

2017-08-10 08:19 UTC, nicolaiparlog commented
:+a:

2017-08-10 08:47 UTC, merged