Zufallsentscheidung für jedes Auto
RF-Buerky/BBFW-Project pull request #86
Opened 2017-08-08 23:56 UTC by dbaumy

(Lösung) für Issue #65 
Closes #65 

Ein erster Ansatz für die Wahrscheinlichkeiten liegt vor und der Random-Teil folgt noch. Morgen nehme ich mir ne Auszeit vom Bürojob und versuche hier mehr Code zu liefern.

2017-08-09 08:45 UTC, nicolaiparlog commented
Meld dich mit einem Kommentar, wenn ich es mir angucken kann.

2017-08-09 13:13 UTC, RF-Buerky commented on src/main/kotlin/traffic_simulation/RoadNetwork.kt
> +            in 51..69 -> probabilityOfDelay = 10
Die 50 ist nirgens drin. Zeile 18 müsste lauten:
```kotlin
in 50..69 ->probabilityOfDelay = 10

2017-08-09 13:38 UTC, RF-Buerky commented
Hab eine Idee wie man den Boolean für `delay` von der `probabilty` abhängig machen kann:

```kotlin
        fun randomTrueByChance (probability : Int):Boolean {
            val randomResult : Boolean

            val chanceList : MutableList<Int> = mutableListOf()
            for (i in 1..probability) {
                chanceList.add(i)
                // for example: probability is 30% so now are the numbers 1 to 30 in the list
            }
            val random : Random = Random()
            val randomInt : Int = random.nextInt(100 + 1 ) +1
            // the randomInt number is between 1 and 100

            // if the randomInt number is in the number list, the result is true - the chance for that is 30%
            randomResult = chanceList.contains(randomInt)
            return randomResult
        }

2017-08-09 13:54 UTC, jwustmann commented
Musste zwei mal durchlesen, aber scheint mir schlüssig zu sein 

_Sent from my Samsung SM-G900F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

2017-08-09 14:33 UTC, dbaumy commented on src/main/kotlin/traffic_simulation/RoadNetwork.kt
> +            in 51..69 -> probabilityOfDelay = 10
hab ich bereits gesehen, danke :-)

2017-08-09 14:36 UTC, dbaumy commented
Cool, danke. sowas ähnliches habe ich bisher auch entwickelt 👍

2017-08-09 14:38 UTC, nicolaiparlog commented
Ich krieg bestimmt Ärger, weil meine Lösung kürzer ist, aber was spricht dagegen:

```
val delayed = Random().nextInt(100) < probability
```

?

2017-08-09 14:48 UTC, RF-Buerky commented
Waaaas das ist ja mega kurz ^^

ein + 1  vielleicht noch dazu am Ende, dass man die Spanne 1..100 hat statt wie jetzt 0..99? @nicolaiparlog

2017-08-09 14:50 UTC, nicolaiparlog commented
Programmierer nennen sowas "Off By One Error" - bei Wahrscheinlichkeiten zwischen 0 und 100, who cares, also denke ich lieber nicht genau nach, wie es richtig sein müsste. Ich würde eher `< 80` zu `<= 80` machen, aber das ist Geschmackssache.

2017-08-09 15:10 UTC, jwustmann commented
Mal ganz uneigennützig nachgefragt: 
Im Bewertungsmaßstab heißt es, dass es besser wäre je weniger du eingreifst, @nicolaiparlog. 
Sind diese Lösungen von dir so aufzufassen, dass du auch einfach Spaß dran hast und uns nur einen noch eleganteren Weg aufzeigen willst?

_Sent from my Samsung SM-G900F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

2017-08-09 15:21 UTC, RF-Buerky commented
@dbaumy lad doch mal hoch was du bisher noch geändert hast...

2017-08-09 15:38 UTC, dbaumy commented
Jetzt wäre es vielleicht noch besser die Funktion in die Klasse `Vehicle` zu Verschieben um sie dann in `RoadNetwork` aufzufufen.

2017-08-09 15:39 UTC, RF-Buerky commented on src/main/kotlin/traffic_simulation/RoadNetwork.kt
> +        fun DelayedByProbability(probability: Int): Boolean {
Die Funktionsdeklaration hast du gerade noch in einer anderen Funktion drinnen. Fände es besser wenn die Funktion außerhalb wäre. Aber mit der kurzen Version von @nicolaiparlog brächte man die Funktion ja garnicht mehr.

2017-08-09 15:40 UTC, dbaumy commented on src/main/kotlin/traffic_simulation/RoadNetwork.kt
> +        fun DelayedByProbability(probability: Int): Boolean {
spart Speicherplatz, und der ist teuer 💸

2017-08-09 16:22 UTC, dbaumy commented
müsste richtig sein?
wenn nun neben überschrittener Kapazität auch zusätzlich `delayed` true ist wird die Funktion `getDelayedAtHour( )` aufgerufen die wiederum prüft ob das Fahrzeug überhaupt in Stunde x fahren möchte.

2017-08-09 16:40 UTC, dbaumy commented
@RF-Buerky Ich fand deine Lösung kreativ 🚀 
Und auch diesen Ansatz gut:
`val random : Random = Random()
val randomInt : Int = random.nextInt(100 + 1 ) +1`
Denn wenn  man jetzt nicht wie hier einfach zwischen 1 und 100 sich etwas ausgeben möchte kann man auch  dabei auch zwischen beliebigen Werten wählen:
`
fun random_int (max: Int, min: Int): Int {
           return ((Math.random()*(max-min))+min).toInt()
}
`

2017-08-09 17:21 UTC, dbaumy commented
@nicolaiparlog, kannst es dir ansehen.

2017-08-09 18:33 UTC, RF-Buerky commented on src/main/kotlin/traffic_simulation/RoadNetwork.kt
> +        val delayed: Boolean = Random().nextInt(100) <= probabilityOfDelay
also wenn ich diktieren würde, hätten wir hier die +1 noch stehen. Reine Maniküre, müssen gewiss nicht.

So hat man halt für `probabilityOfDelay = 5` einen Treffer bei 0, 1, 2, 3, 4, 5 - das sind 6 Werte statt 5. Würde die Zeile so aussehen: 
```kotlin
val delayed: Boolean = Random().nextInt(100) + 1 <= probabilityOfDelay
```
... hätte man nur 5 Werte und trifft die 5 % haargenau

2017-08-09 18:57 UTC, RF-Buerky commented
Beim Mergen müssen wir aufpassen dass alles an den richtigen Ort kommt. Auf dem master ist nämlich die Funktion `calculateDemandForTimestepAndCauseTrafficJam` schon in mehrer Unterfunktionen aufgespalten worden.

2017-08-10 08:11 UTC, nicolaiparlog commented
> Im Bewertungsmaßstab heißt es, dass es besser wäre je weniger du eingreifst, @nicolaiparlog.
Sind diese Lösungen von dir so aufzufassen, dass du auch einfach Spaß dran hast und uns nur einen noch eleganteren Weg aufzeigen willst?

Jeder Kommentar meinerseits kostet euch eine Teilnote. :wink: Ne ernsthaft, damit meinte ich Situationen, in denen ich was ändern muss, weil es von alleine nicht weitergeht bzw. nur so schlecht weitergeht, dass eure späteren Chancen darunter stark leiden. Das war bis jetzt ganz selten der Fall und bei euch noch gar nicht.

Alles andere sind nur Tipps - ihr sollt ja was lernen.

2017-08-10 08:17 UTC, nipafx requested changes
Ein paar Problemchen gibt es noch:

2017-08-10 08:17 UTC, nicolaiparlog commented on src/main/kotlin/traffic_simulation/RoadNetwork.kt
> +        val percentOfCapacityUsage: Int = (demandAtTimestep / capacity) * 100
Bist du sicher, dass das funktioniert? Erinner dich an die erste Vorlesung - da gab es mal die Erkenntnis, dass wenn Integer geteilt werden, dabei immer Integer rauskommen (und zwar abgerundet). Das gilt für jeden einzelnen Rechenschritt, d.h. ich vermute, dass `demandAtTimestep / capacity` und deswegen auch `percentOfCapacityUsage` immer `0` ist.

2017-08-10 08:17 UTC, nicolaiparlog commented on src/main/kotlin/traffic_simulation/RoadNetwork.kt
> +            !in Int.MIN_VALUE..Int.MAX_VALUE -> println("insane road")
Das brauchst du nicht, ein Integer ist immer zwischen dem kleinsten und größten Wert.

2017-08-10 08:17 UTC, nicolaiparlog commented on src/main/kotlin/traffic_simulation/RoadNetwork.kt
> +        val delayed: Boolean = Random().nextInt(100) + 1 <= probabilityOfDelay
Ich würde die gesamte Wahrscheinlichkeitsberechnung in eine eigene Methode stecken.

2017-08-10 08:17 UTC, nicolaiparlog commented on src/main/kotlin/traffic_simulation/RoadNetwork.kt
> +        if (demandAtTimestep > capacity && delayed) {
Die Prüfung `demandAtTimestep > capacity` ist falsch: wenn `delayed`, dann verspätet, auch unter Kapazität.

2017-08-10 08:17 UTC, nicolaiparlog commented on src/main/kotlin/traffic_simulation/RoadNetwork.kt
> +            for (vehicle in vehicleList) {
Offene Frage: wie oft bestimmst du zufällig, ob es zu Verspätungen kommt und für wie viele Fahrzeuge gilt die Entscheidung dann?

2017-08-10 08:41 UTC, RF-Buerky commented on src/main/kotlin/traffic_simulation/RoadNetwork.kt
> +        val percentOfCapacityUsage: Int = (demandAtTimestep / capacity) * 100
Ah ja. Vielleicht dann erst einen Double ausrechnen und diesen zu einem Int machen.

2017-08-10 08:44 UTC, RF-Buerky commented on src/main/kotlin/traffic_simulation/RoadNetwork.kt
> +        if (demandAtTimestep > capacity && delayed) {
Ja, die Abhängigkeit von `capacity` steckt in der Berechnung des Boolean drin.

2017-08-10 08:46 UTC, RF-Buerky commented on src/main/kotlin/traffic_simulation/RoadNetwork.kt
> +            for (vehicle in vehicleList) {
Man bestimmt für jedes `Vehicle` einzeln ob es sich verspäten wird, sofern es fahren will (wannaDriveInHour den timestep enthält der delay abzubauen ist).

2017-08-10 10:25 UTC, nicolaiparlog commented on src/main/kotlin/traffic_simulation/RoadNetwork.kt
> +            for (vehicle in vehicleList) {
@RF-Buerky So _soll_ es sein - wie _ist_ es im Code?

2017-08-10 10:38 UTC, RF-Buerky commented on src/main/kotlin/traffic_simulation/RoadNetwork.kt
> +            for (vehicle in vehicleList) {
Aktuell wird einmal der Boolean ausgerechnet und auf alle Fahrzeuge angewendet.

2017-08-10 10:41 UTC, dbaumy commented on src/main/kotlin/traffic_simulation/RoadNetwork.kt
> +        val percentOfCapacityUsage: Int = (demandAtTimestep / capacity) * 100
Natürlich, ich habe mir gestern das noch angeschaut und printen lassen. Aber da hab ich es übersehen. :-/

_Sent from my Samsung SM-G920F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

2017-08-10 10:42 UTC, nicolaiparlog commented on src/main/kotlin/traffic_simulation/RoadNetwork.kt
> +            for (vehicle in vehicleList) {
> "Excellent! I cried.
> "Elementary," said he.

Das muss gefixt werden.

2017-08-10 10:43 UTC, jwustmann commented on src/main/kotlin/traffic_simulation/RoadNetwork.kt
> +            for (vehicle in vehicleList) {
Mein Vorschlag:

Die Methode in `Vehicle` einbauen, und ihr den Parameter für` Demand` und `Capacity` übergeben. Je nach Quotient wird mit einer gewissen Wahrscheinlichkeit ein `true` zurückgegeben. Beim Aufruf der Methode dann: 
`if (xy(1,2))
{gettingDelayed()
}`
So würde jedes Auto einzeln berechnet im Hinblick auf die Verspätung, nicht zentral

2017-08-10 10:43 UTC, dbaumy commented on src/main/kotlin/traffic_simulation/RoadNetwork.kt
> +        if (demandAtTimestep > capacity && delayed) {
Okay, Danke. Ich schaue es mir später an. Bin noch auf der Arbeit.

_Sent from my Samsung SM-G920F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

2017-08-10 10:44 UTC, nicolaiparlog commented on src/main/kotlin/traffic_simulation/RoadNetwork.kt
> +            for (vehicle in vehicleList) {
:+1:

2017-08-10 15:29 UTC, RF-Buerky commented
Nach diesem Zufalls-Update kann man die Sumulation ja kaum mehr durch Tests testen, oder?

Ein einzelnes Simulationsergebnis bestimmt kaum. Man könnt vielleicht die Sache 100mal durchlaufen lassen und am Ende gucken ob bei jeweiliger Auslastung etwa 5mal bzw. 30mal bzw. xmal `delayed` wurde.

2017-08-10 16:15 UTC, jwustmann commented
Den Zufall reproduzierbar testen.   Klingt paradox.

Die einzige Idee die ich hätte:
Ein Konfidenzintervall angeben, sodass die Mehrheit der Tests um den Erwartungswert liegt.

Damit der Test immer funktioniert und nicht nur ab und zu, könnte man das Intervall lächerlich groß wählen  (z.B. 6 Sigma), was wiederum die Sinnhaftigkeit des Tests infrage stellt. 

Mein Vorschlag: Alle Funktionen die zuverlässig reproduziert werden können auch testen,  die anderen nicht 



_Sent from my Samsung SM-G900F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

2017-08-10 16:24 UTC, RF-Buerky commented
Ja genau so meint ich das auch. Einen Ticker mitzählen lassen wie oft delayed wurde und diese Zahl soll dann innerhal beiner Spanne sein. Z.b. zwischen 3 und 7 wenn 5% gefordert sind.

2017-08-10 16:57 UTC, jwustmann commented
Idee: Wir verursachen einen Stau in Stunde mit vielen Autos (fahren nur in der ersten Stunde), schauen ob mindestens eins in der nächsten Stunde fahren wird wegen Stau. Dann schauen wir ob in der letzten Stunde der Stau aufgelöst ist.
Das prüft die Abläufe auf Funktionalität und gelingt mit hoher Wahrscheinlichkeit, ohne zu exakte zahlen vorauszusetzen.

Was die Wahrscheinlichkeiten angeht würde ich einfach den Code ansehen und dann gut sein lassen.

Bis der counter einen statistisch signifikanten Fehler anzeigen würde, der durch einen kleinen Code Fehler verursacht wird (Bsp ein Int ist nicht in der gesamt laute abgedeckt, wie es der Fall war) müsste die csv so groß sein, dass es hier vermutlich deutlich der ahmen sprengt.


_Sent from my Samsung SM-G900F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

2017-08-10 17:32 UTC, dbaumy commented
wenn man sowieso unabhängig von `demandAtTimestep > capacity` zufällig die verspätung zuteilt, dann brauch man doch garincht mehr die funktion zur Ermittlung des Staus (`trafficJam`)?!

2017-08-10 17:40 UTC, RF-Buerky commented
Ja stimmt

2017-08-10 18:04 UTC, dbaumy commented
Ich hatte meinen Master updated und einen branch namens random3 erstellt und an dem nun gearbeitet. jetzt hab ich gepushed und ... wie verknüpfe ich das jetzt mit diesem PR?

2017-08-10 18:58 UTC, nicolaiparlog commented
Re den Zufall testen. Dazu gibt es Tricks. Was haltet ihr davon, wenn ihr das hier mergt und ein Issue für den naechsten Block erstellt, und dann helfe ich jemandem das zu implementieren.

Re GitHubs Bescherde über Konflikte: Das kann ich lösen, aber dafür müsst ihr mir sagen, wann gerade keiner mehr lokale Änderungen hat, die nicht auf den Branch gepusht sind. Mein Rumgefummel macht es nämlich schwer, die dann noch hier unterzubringen.

> Ich hatte meinen Master updated und einen branch namens random3 erstellt und an dem nun gearbeitet. jetzt hab ich gepushed und ... wie verknüpfe ich das jetzt mit diesem PR?

Gar nicht, du haettest auf `random2` pushen müssen. Wenn du `random3` von `random2` aus angelegt hattest, bekämen wir das noch hin, aber so sieht's schlecht aus.

2017-08-10 19:04 UTC, nicolaiparlog commented
Ich sehe gerade, dass noch Änderungen ausstehen und @dbaumy erstmal keine Zeit. Falls jemand anders an diesem Branch weiterarbeiten will, das geht so:

* mit scharfem Auge sehen, dass GitHub sagt:
    > "Add more commits by pushing to the [random2](https://github.com/dbaumy/BBFW-Project/tree/random2) branch on [dbaumy/BBFW-Project](https://github.com/dbaumy/BBFW-Project)."
* auf den zweiten Link klicken und dort die Adresse zum Clonen herausfinden
* lokal in eurem Git Repo:
    ```
    # dbaumy's Fork als Remote hinzufügen
    git remote add fork-dbaumy $URL
    # gucken was in dem Fork so los ist
    git fetch fork-dbaumy
    # diesen Branch hier auschecken
    git checkout random2
    ```
* ganz normal arbeiten und pushen

Dabei kann man sich schnell gegenseitig auf die Füße treten und wir haben noch nicht besprochen, wie man sowas wieder auflöst. Sprecht euch also ab.

2017-08-10 19:30 UTC, RF-Buerky commented
Ich probiers ma und lade gleich einen Mini-Test-Commit hoch.

2017-08-10 19:34 UTC, RF-Buerky commented
Ok super, funktioniert. Werde aber dann auch den anderen Zweig und anderen PullRequet von @dbaumy wechseln. Dort hat er noch einige Änderungen vorgenommen.

2017-08-10 20:29 UTC, RF-Buerky commented
Dieser PullRequest wurde durch PullRequest #88 ersetzt.

2017-08-10 22:09 UTC, closed without merging